# Generated by Django 4.2.4 on 2023-08-18 14:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('contacts', '0002_alter_contact_phone'),
    ]

    operations = [
        migrations.AddIndex(
            model_name='contact',
            index=models.Index(fields=['phone'], name='contacts_co_phone_5a60c7_idx'),
        ),
    ]
