# Generated by Django 4.2.4 on 2023-08-18 14:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('spam_reports', '0002_spamreport_name'),
    ]

    operations = [
        migrations.AddIndex(
            model_name='spamreport',
            index=models.Index(fields=['phone'], name='spam_report_phone_48c53e_idx'),
        ),
    ]
